---
apiVersion: v1
kind: Deployment
metadata:
  name: nginx-test
  namespace: test-image
  labels:
    app: nginx-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
      - name: nginx-test
        image: memobre/nginx:v0.1.0
        ports:
        - containerPort: 80